#!/usr/bin/env python3
"""Create package handoff and size manifests."""

from __future__ import annotations

from pathlib import Path

from full_repro_common import PKG_ROOT, write_csv


OUT_MD = PKG_ROOT / "MANIFEST.md"
OUT_CSV = PKG_ROOT / "audit" / "full_repro" / "file_size_manifest.csv"


def choose_rel(*candidates: str) -> str:
    for candidate in candidates:
        if (PKG_ROOT / candidate).exists():
            return candidate
    return candidates[0]


SPEC_NAMES = [
    "raw_response_schema.yaml",
    "parser_spec.yaml",
    "endpoint_definitions.yaml",
    "axis_book.yaml",
    "eligibility_rules.yaml",
    "metric_definitions.yaml",
    "split_mask_spec.yaml",
    "reconstructor_spec.yaml",
    "null_spec.yaml",
]

DOCS = [
    ("docs/REPRODUCTION_CLAIM.md", "FULL_REPRO_CLAIM.md"),
    ("docs/CLAIM_BOUNDARY.md", "CLAIM_LANGUAGE.md"),
    ("docs/SUMMARY_FOR_REVIEWERS.md", "REVIEWER_SUMMARY.md"),
    ("docs/METHODS_QA_CHECKLIST.md", "REVIEWER_QA_14_POINT_CHECKLIST.md"),
    ("REPRODUCING.md", "INDEPENDENT_REPRODUCTION_INSTRUCTIONS.md"),
    ("docs/DATA_USE.md", "DATA_USE.md"),
    ("docs/DATA_ACCESS.md", "DATA_ACCESS.md"),
    ("docs/CODEBOOK.md", "CODEBOOK.md"),
]

OPTIONAL_ROOT_INPUTS = [
    "pyproject.toml",
]

REQUIRED_INPUTS = [
    "data/raw/raw_input_manifest.csv",
    "data/raw/source_artifacts/cross_model/inference",
    "data/raw/source_artifacts/cross_model/DataOriginal_FINAL.csv",
    "data/raw/source_artifacts/gpt_health/DataOriginal_FINAL.csv",
    "data/canonical",
    "README.md",
    "MANIFEST.md",
    "LICENSE",
    "CITATION.cff",
    "Dockerfile",
    "Makefile",
    "environment.yml",
    choose_rel("code/run_full_repro.sh", "run_full_repro.sh"),
    choose_rel("code/run_all.sh", "run_all.sh"),
]
REQUIRED_INPUTS.extend(
    choose_rel(f"data/specs/{name}", f"specs/{name}") for name in SPEC_NAMES
)
REQUIRED_INPUTS.extend(choose_rel(*paths) for paths in DOCS)
REQUIRED_INPUTS.extend(path for path in OPTIONAL_ROOT_INPUTS if (PKG_ROOT / path).exists())

KEY_OUTPUTS = [
    "results/full_repro/main_result_table.csv",
    "results/full_repro/per_model_results.csv",
    "results/full_repro/denominator_table.csv",
    "results/full_repro/endpoint_audit_table.csv",
    "results/full_repro/null_distribution_raw_recomputed.csv",
    "audit/full_repro/null_recompute_vs_frozen_report.md",
    "audit/full_repro/raw_rebuild_vs_canonical_artifact_report.md",
    "audit/full_repro/endpoint_attempt_ledger.csv",
]

LARGE_REPRODUCIBLE_OUTPUTS = [
    "results/full_repro/parsed_responses.csv",
    "results/full_repro/hidden_predictions.csv",
    "results/full_repro/null_permutation_manifest.csv",
    "data/splits/full_repro/q12_split_manifest.csv",
]

OPTIONAL_HANDOFF_OUTPUTS = [
    "audit/full_repro/strict_clean_run_terminal_transcript.txt",
]


def size(path: Path) -> int:
    if path.is_dir():
        return sum(item.stat().st_size for item in path.rglob("*") if item.is_file())
    return path.stat().st_size if path.exists() else 0


def human(n: int) -> str:
    units = ["B", "KB", "MB", "GB"]
    value = float(n)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{n} B"


def row(path_text: str, category: str) -> dict[str, object]:
    path = PKG_ROOT / path_text
    return {
        "path": path_text,
        "category": category,
        "exists": path.exists(),
        "size_bytes": size(path),
        "size_human": human(size(path)),
        "regeneration": "generated by run_full_repro.sh --strict"
        if category != "required_input_or_spec"
        else "required source/spec",
    }


def main() -> None:
    rows = []
    rows.extend(row(path, "required_input_or_spec") for path in REQUIRED_INPUTS)
    rows.extend(row(path, "key_generated_output") for path in KEY_OUTPUTS)
    rows.extend(row(path, "large_reproducible_output") for path in LARGE_REPRODUCIBLE_OUTPUTS)
    rows.extend(row(path, "optional_handoff_output") for path in OPTIONAL_HANDOFF_OUTPUTS)
    write_csv(
        OUT_CSV,
        ["path", "category", "exists", "size_bytes", "size_human", "regeneration"],
        rows,
    )

    md = [
        "# Handoff Manifest",
        "",
        "Run the strict reproduction:",
        "",
        "```sh",
        f"bash {choose_rel('code/run_full_repro.sh', 'run_full_repro.sh')} --strict",
        "```",
        "",
        "## Required Inputs And Specs",
        "",
    ]
    for path in REQUIRED_INPUTS:
        md.append(f"- `{path}`")
    md.extend(["", "## Key Generated Outputs", ""])
    for path in KEY_OUTPUTS:
        p = PKG_ROOT / path
        md.append(f"- `{path}` ({human(size(p))})")
    md.extend(["", "## Large Reproducible Outputs", ""])
    for path in LARGE_REPRODUCIBLE_OUTPUTS:
        p = PKG_ROOT / path
        md.append(f"- `{path}` ({human(size(p))})")
    md.extend(
        [
            "",
            "Large outputs are retained for forensic review but are reproducible from the strict runner.",
            "Do not delete them for a review bundle unless the reviewer agrees to regenerate outputs locally.",
        ]
    )
    md.extend(["", "## Optional Handoff Outputs", ""])
    for path in OPTIONAL_HANDOFF_OUTPUTS:
        p = PKG_ROOT / path
        status = human(size(p)) if p.exists() else "not present"
        md.append(f"- `{path}` ({status})")
    OUT_MD.write_text("\n".join(md))

    missing = [
        r["path"]
        for r in rows
        if not r["exists"] and r["category"] != "optional_handoff_output"
    ]
    if missing:
        raise SystemExit(f"Handoff manifest missing files: {missing}")
    print(f"Handoff manifest written for {len(rows)} tracked files.")


if __name__ == "__main__":
    main()
